### ISSUE TITLE
03. 자바와 객체 지향

### ISSUE THREAD

**Issue by yshjft** [VictoryKids/Victory-Frog#2]
3장 질문을 올려 주세요.

**Comment by yshjft** [comment]
ㅁ

**Comment by yshjft** [comment]
책 98페이지를 보면 ```mickey.sing()```을 호출할 때 T메모리 상의 변화는 없다고 합니다. 메서드를 호출하게 되면 스택 영역에 해당 메서드에 대한 스택 프레임이 생기는거 아닌가요?

**Comment by Pawer0223** [comment]
p.135 ~ 140에서 `캡슐화:정보은닉` 에 대해 설명하고 있는데요. 객체 멤버 vs static 멤버일 때 사용되는 접근 제어자에 대한 내용이 대부분 입니다.<br>
그래서 정보은닉이란 무엇을 의미하는걸까요? 접근제어 지시자를 적절히 사용하면 정보은닉을 할 수 있다는 의미일까요 ?<br>
그렇다면 public 지시자를 올바르게 사용했다면 정보은닉을 잘 했다고(?) 표현할 수 있을까요?<br>

**Comment by julie0005** [comment]
상속과 인터페이스에 관해서

부모클래스의 메소드를 자식 클래스가 오버라이딩하여 재정의하는 것이 인터페이스의 디폴트 메소드를 구현체에서 오버라이딩하는 것과 같은 기능을 하는 것 같습니다. 각각의 경우는 어떨 때에 사용해야 올바르게 사용하고 있는 걸까요?

**Comment by julie0005** [comment]
> 책 98페이지를 보면 `mickey.sing()`을 호출할 때 T메모리 상의 변화는 없다고 합니다. 메서드를 호출하게 되면 스택 영역에 해당 메서드에 대한 스택 프레임이 생기는거 아닌가요?

저도 궁금한 부분입니다!

**Comment by julie0005** [comment]
책에서는 인터페이스가 is able to로 사용하면 좋다고 말하고 있지만 현실에서는 able이 아닌 명사형 인터페이스도 많이 보입니다. 예제 코드로 작성했던 Voucher Interface도 그렇구요! 
1. FixedAmountVoucher is able to Voucher  
2. FixedAmountVoucher is kind of Voucher

2번이 더 어울려 보이기도 합니다. 그러면 Voucher는 interface보다 class로 정의하는 것이 더 좋은 선택인걸까요? is kind of이 더 어울리는 인터페이스도 많이 보이는 이유는 무엇일까요?

**Comment by julie0005** [comment]
JVM이 생각보다 복잡하네요..!

일단 멘토님이 질문하셨던 인스턴스 메소드는 인스턴스마다 만들어지는 것이 아닌, 클래스마다 하나의 공간을 차지하는 것으로 보입니다. 구현은 Method Area의 Method Info에 클래스 당 하나로 되어있고, Instance들은 클래스의 메소드를 가리키는 포인터 변수 공간을 Method Table에 가지게 되네요! 책에서 말하는 JVM의 T메모리구조는 실제 JVM 구조를 간략화한 것으로 보이고, method와 기타 클래스 데이터들을 Method Area라는 영역에 저장하네요! 

클래스가 인스턴스화되면 메소드를 가리키는 ptr을 method table에 저장하고, 인스턴스 method를 실행하면 method table을 탐색하며 해당 method가 가리키는 주소, method info에서 method를 실행하는 원리인 것 같습니다. 주말에 공부해서 포스팅으로 올려볼게요! 탐구하기 좋은 주제네요 ^~^

https://docs.oracle.com/javase/specs/jvms/se15/html/jvms-2.html#jvms-2.5.4
https://mia-dahae.tistory.com/101

**Comment by Pawer0223** [comment]
처음엔 책 내용으로만 이해했는데 승은님이 정리해주신 내용보고 조금 더 찾아보았습니다.

- [참조](https://smoothiecoding.kr/%EC%9E%90%EB%B0%94-%EA%B0%80%EC%83%81-%EB%A9%94%EC%86%8C%EB%93%9C/)

제가 생각한 해당 질문의 핵심 키워드는 `코드, 데이터 영역의 구분`과 `자바 가상 메소드`인것 같습니다.

저는 참조 링크의 아래 내용에서 이해할 수 있었습니다. ㅎ

프로그램을 크게 두 부분으로 나누면 코드와 데이터가 됩니다. 메소드는 코드이므로 메모리상의 코드세그먼트에 저장됩니다. 같은 클래스의 메소드는 한번만 저장하면 충분하고 인스턴스는 여러개가 될 수 있으니 여러개의 인스턴스는 하나의 메소드(코드 세그먼트)를 가리키게 됩니다.
인스턴스와 메소드를 연결하기 위해서 클래스의 메타 데이터에는 가상 메서드 테이블이 있습니다. 이것으로 인스턴스를 메소드에 연결 시켜주는 것 입니다.
