### ISSUE TITLE
04. 자바가 확장한 객체지향

### ISSUE THREAD

**Issue by yshjft** [VictoryKids/Victory-Frog#4]
4장 질문 올려주세요.

**Comment by sdardew** [comment]
instanceof는 실무에서는 사용하지 않는 키워드인가요?

**Comment by julie0005** [comment]
실무에서 Supplier와 Consumer 등 함수형 인터페이스를 적극적으로 사용하는지 궁금합니다.

**Comment by Pawer0223** [comment]
> instanceof는 실무에서는 사용하지 않는 키워드인가요?
- instanceof는 주로 나쁜 디자인(설계)에서 사용되고, 크고 복잡한 분기처리가 뒤따를 것이라는 확실한 신호라고 합니다. 그래서 실무에서도 instanceof의 사용을 지양하는것 같습니다.
- [참조](https://stackoverflow.com/questions/3776862/when-should-and-shouldnt-instanceof-be-used)

**Comment by Pawer0223** [comment]
> 실무에서 Supplier와 Consumer 등 함수형 인터페이스를 적극적으로 사용하는지 궁금합니다.

함수형 프로그래밍이 자주 사용되면서 Supplier와 Consumer가 자주 활용되는것 같습니다. 멘토님께서도 자주 활용된다고 첨언주셨습니다 ㅎ
